"""Initial migration

Revision ID: 0997eedde53d
Revises: 
Create Date: 2024-08-31 18:48:46.375343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0997eedde53d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('nombre_carrera', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_carrera')
    )
    op.create_table('leads',
    sa.Column('id_lead', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_lead')
    )
    op.create_table('materias',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre_materia', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('inscripciones',
    sa.Column('id_inscripcion', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('materia_id', sa.Integer(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.Column('anio_inscripcion', sa.Integer(), nullable=True),
    sa.Column('nro_veces_cursada', sa.Integer(), nullable=True),
    sa.Column('tiempo_cursado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id_carrera'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id_lead'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id_materia'], ),
    sa.PrimaryKeyConstraint('id_inscripcion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscripciones')
    op.drop_table('materias')
    op.drop_table('leads')
    op.drop_table('carreras')
    # ### end Alembic commands ###
